Bug 28725: Upgrade go-webrtc to dcbfc825aa33471253a5da1834d499257e05d557.
This necessitates an upgrade to webrtc to branch-heads/64. Compare to:
https://github.com/keroserene/go-webrtc/commit/1ca4087bc01b9a6726a68c72ac541b03a91c4c7b

-D_GLIBCXX_USE_CXX11_ABI=1 is no longer required, as the default has
changed:
https://github.com/keroserene/go-webrtc/commit/a3140c36f9933013ad2e66bc21358a1bfea95a95

I needed to add libgtk-3-dev as a build dependency for webrtc.
libgtk-3-dev appears in src/build/install-build-deps.sh.

I also had to upgrade depot_tools to
7d9d9233cb657e968831238346917b0b64abb4c1. I got the commit ID from
src/DEPS in the webrtc source. Without upgrading depot_tools, I got this
error from gclient:
	Error: 1> dependency url must be either a string, None, File() or From() instead of dict

I needed to add a command to delete src/testing/{gmock,gtest}; otherwise
"gclient sync" complains about overwriting unversioned files.
https://bugs.torproject.org/25483#comment:15
https://gitweb.torproject.org/user/boklm/tor-browser-build.git/commit/?h=bug_25483_v0&id=d5514f7f3b566cf37bfc59ec8105a96130577ff2
The error is
	src/testing (ERROR)
	----------------------------------------
	[0:00:00] Started.
	[0:00:01] From https://chromium.googlesource.com/chromium/src/testing
	[0:00:01]    7d7436a8..9805faa0  master     -> origin/master
	----------------------------------------
	Error: Command 'git checkout --quiet 60c665fffe7dc505fdd5d30f9dbcbc50dde1e017' returned non-zero exit status 1 in /home/user/tor-browser-build/gclient/webrtc/src/testing
	error: The following untracked working tree files would be overwritten by checkout:
		gmock/include/gmock/gmock-actions.h
		gmock/include/gmock/gmock-generated-function-mockers.h
		gmock/include/gmock/gmock-matchers.h
		gmock/include/gmock/gmock.h
		gtest/include/gtest/gtest-death-test.h
		gtest/include/gtest/gtest-message.h
		gtest/include/gtest/gtest-param-test.h
		gtest/include/gtest/gtest-spi.h
		gtest/include/gtest/gtest.h
		gtest/include/gtest/gtest_prod.h
	Please move or remove them before you switch branches.
	Aborting